apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: demotomcatpod 
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: demotomcatpod 
  template:
    metadata: 
      labels:
        app: demotomcatpod
    spec:
      containers:
      - name: demotomcatpod
        image: 1212122345/dockerjenkinsdemo:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: demotomcatpod-svc 
  labels:
    app: demotomcatpod 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: demotomcatpod
